### ISSUE TITLE
Please help with the Help.

### ISSUE THREAD

**Issue by Briseur** [andimachovec/Peggy#10]
Sorry, I couldn't resist.
![Peggyhelp](https://user-images.githubusercontent.com/37412120/187493392-10a264c9-2f9a-4437-9f2a-9294891a6e82.png)

I can't figure out if this is because of my colour scheme but there's something wrong here...
Black is white and white is green. lol

**Comment by Briseur** [comment]
This is indeed a question of colour scheme. To avoid that, colour of pins should be fixed. 

![Peggy-Help-Light](https://user-images.githubusercontent.com/37412120/187633102-53bd10cb-6e10-4076-a6f4-d2e6214f7a36.png)

**Comment by andimachovec** [comment]
Hi Briseur, 

Thanks for reporting for what at first may seem like a major bug in Peggy ;-)

The black and white dots used in the help text are the unicode characters for "medium black circle" and "medium white circle", respectively (UTF8 hex codes e29aab and e29aaa). They are taken as string literals from the c++ code. So either your colour scheme is wrong or there is an error in the way Haiku handles the colour schemes. 

Btw, this also serves as a good example why I'm against changing colour schemes in the first place ;-)

**Comment by Briseur** [comment]
As you can see, it only happens in the help. 
![Peggy](https://user-images.githubusercontent.com/37412120/188816625-328328e7-a83a-4942-a459-5032d598cb1a.png)
I guess that Haiku colourize UTF8 characters like if they were text without distinction.
I didn't found a Trac ticket about that so, I created a [new one](https://dev.haiku-os.org/ticket/17936)

**Comment by andimachovec** [comment]
The UTF-8 characters I was referring to are only used in the help text. The pegs in the actual game (and the whole game board) are drawn via the Haiku API and are not affected by any colour scheme. The only exceptions are where standard controls are used, like the button or the elapsed time display.
