### ISSUE TITLE
Menu improvement

### ISSUE THREAD

**Issue by Briseur** [andimachovec/Peggy#12]
Naming the menu App is not that elegant.
Pehaps would it be better to use Peggy icon instead, as humdinger did for Quicklaunch?

**Comment by andimachovec** [comment]
IIRC, humdinger suggested naming the App menu ;-) I'll keep it that way. Regardless of how I name the menu, not everyone will like it. And it is not really important to me. 

Anyway, thanks for your interest in Peggy ;-)
