### ISSUE TITLE
Create a help file

### ISSUE THREAD

**Issue by humdingerb** [andimachovec/Peggy#5]
I'm willing to work on that. I may have questions popping up while writing the doc that I'll add to this ticket.

Q: The result pegs are grouped 2 by 2. Do they correespond to the code-peg positions like this:

```
result       code
1 2             1  2  3  4
3 4
```

**Comment by andimachovec** [comment]
Sorry, must have overlooked the question before. The position of the result peg does not correspond to the peg it is relating to. At first, when submitting the row, the number of black and white pegs is calculated. Then pegs are drawn in lines starting from top left, beginning with the black pegs. 
Putting the result pegs in corresponding positions is a common beginner´s mistake in the actual board game. 

Anyway, you already explained it correctly in your help text.
