### ISSUE TITLE
Row gets auto-completed when moving a peg back to stock

### ISSUE THREAD

**Issue by humdingerb** [andimachovec/Peggy#6]
When you move a peg back from the active row to the 'stock' at the right, the row gets automatically completed. The active row moves one up.

(BTW: can empty slots be part of a regular code, or do we can assume to always have four coloured pgs in a code?)

**Comment by andimachovec** [comment]
Oh, wow. That´s surprising to me. This is clearly a bug. Must have been introduced quite late in the initial development. When I did the drag and drop testing it definitely wasn´t there. Will take a look at it. 
As for the empty slots: There are always 4 colours in the code, and a row has to be completely filled to be able to submit it.

**Comment by andimachovec** [comment]
That was a good one :-) . Accidentally used identical whatcodes in 2 different views. One of them was the "complete row" button. Fixed in 0.7.2

**Comment by humdingerb** [comment]
A quick to fix bug then, nice! :)
